name: Starred Topics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          user: ${{ github.repository_owner }}
          template: classic
          committer_branch: main
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: assets/metrics.plugin.topics.svg
          
          # Topics Plugin Configuration
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_sort: stars
          plugin_topics_limit: 12